#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Koumei Ainoya
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans=0
sa=0
seki=1
syou=1

for line in sys.stdin:
    ans += tonum(line)
    sa -= tonum(line)
    seki *= tonum(line)
    syou /= tonum(line)

print("和＝" ans "差＝" sa "積＝" seki "商＝" syou )
